name: tfmigrate apply
description: tfmigrate apply
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@pr/516
      id: target-config
    - run: bash ${{ github.action_path }}/main.sh
      working-directory: ${{ steps.target-config.outputs.working_directory }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_APP_TOKEN: ${{ inputs.github_app_token }}
